version: "3"

services:
  etcd:
    image: docker.io/bitnami/etcd:3.4.13
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 9500:2379
    volumes:
      - etcd_data:/bitnami/etcd

  consul:
    image: docker.io/consul:1.8
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -dev -client 0.0.0.0 -ui
    # - agent
    # - -server
    # - -bind 0.0.0.0
    # - -dev
    # - -ui
    ports:
      - 8500:8500
    volumes:
      - consul_data:/consul/data
volumes:
  etcd_data:
    driver: local
  consul_data:
    driver: local
